### PR TITLE
Fix error display bug and styling

### LINKED ISSUE #50: Make UrlRef work with other types
Obviously putting a complete object in the url is pretty unreasonable, but making boolean and number work natively would be pretty great

### PR DESCRIPTION
**Pull request by YouSafe**
Fix #50

### CODE REVIEW

**Comment by stefnotch** [comment]
Relevant https://github.com/tuwien2020/tgi-pages/pull/45

File: src/url-ref.ts [hunk 1]
```diff
@@ -1,20 +1,41 @@
...
 import { RouteLocationNormalized, Router } from "vue-router";
 
 export function useUrlRef(router: Router, route: RouteLocationNormalized) {
-  function urlRef(name: string, defaultValue: string): Ref<string> {
-    const value = ref<string>("" + (route.query[name] ?? defaultValue));
+  function urlRef(name: string, defaultValue: boolean): Ref<boolean>;
+  function urlRef(name: string, defaultValue: string): Ref<string>;
+  function urlRef<T extends string | boolean>(name: string, defaultValue: T): Ref<T> {
+    // Parse the value in the URL
+    const type = typeof defaultValue;
```
Comment (Fancy11111) [inline src/url-ref.ts:10]: this leads to problems when loading a page without url extensions, try the truth table for example, that now starts with undefined in the input field

Comment (Fancy11111) [reply src/url-ref.ts:10]: I implemented a fix, please review if possible

File: src/pages/TruthTable.vue [hunk 2]
```diff
@@ -183,8 +183,8 @@ export default defineComponent({
 
     const tableHeaders = shallowRef<MathJson[]>([]);
     const tableRows = ref<boolean[][]>([[]]);
-    const flipBits = ref<boolean>(false); // TODO: Make urlRef
-    const hideColumns = ref<boolean>(false); // TODO: Make urlRef
+    const flipBits = urlRef("flipped",false);
+    const hideColumns = urlRef("hideExtra",false);
```
Comment (stefnotch) [inline src/pages/TruthTable.vue:187]: Could this be changed to `hide-extra`, just to follow the typical convention for URL query params?

File: src/pages/HammingCode.vue [hunk 3]
```diff
@@ -60,17 +58,20 @@ export default defineComponent({
     const { urlRef } = useUrlRef(router, route);
 
     const code = urlRef("code", "");
-    // TODO: make urlRef support booleans
-    const dataOnly = urlRef("dataOnly", "false");
+    const dataOnly = urlRef("dataOnly", false);
+
+    // url cleanup
+    code.value = code.value.replace(/[^01]/g, '');
+    console.log(dataOnly.value);
```
Comment (stefnotch) [inline src/pages/HammingCode.vue:65]: Let's remove the console.log before merging this

File: src/url-ref.ts [hunk 4]
```diff
@@ -1,20 +1,50 @@
...
+      const maybeBoolean = routeParamVal + "";
+      if (maybeBoolean === "1" || maybeBoolean === "true") {
+        startingValue = true;
+      } else if (maybeBoolean === "0" || maybeBoolean === "false") {
+        startingValue = false;
+      }
+    }
+    else if (type === "number") {
+      if(routeParamVal !== undefined) {
+        startingValue = Number.parseInt(routeParamVal + "");
```
Comment (stefnotch) [inline src/url-ref.ts:27]: I suppose this is fine, even if `Number.parseInt()` is a bit weird. For example, it will happily parse `Number.parseInt("0xCat")`

File: src/pages/TruthTable.vue (hunk 2 above)
Comment (Fancy11111) [reply src/pages/TruthTable.vue]: done, thx

File: src/pages/HammingCode.vue (hunk 3 above)
Comment (Fancy11111) [reply src/pages/HammingCode.vue]: done :)

File: src/url-ref.ts (hunk 4 above)
Comment (Fancy11111) [reply src/url-ref.ts:27]: yeah true, if you have a better idea thats not tooooo time consuming go ahead

Comment (stefnotch) [reply src/url-ref.ts:27]: I suppose this would be good enough:tm:
```js
if(/^[0-9]+$/.test(routeParamVal + "")) {
   Number.parseInt(routeParamVal + "", 10)
}
```
